name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Build
              run: sh ./build.sh

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: '16.16.0'
                cache: 'yarn'
              

            # - name: Deploy
            #   run: npm run-script deploy
            #   env:
            #       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
